version: '3.8'

services:
  # API Settings
  meli-api:
    build: .
    volumes:
      - ./:/usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo-db

  # MongoDB Settings
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: ["mongod", "--quiet"]
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
